# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-doc-test',
                'doc_host': 'https://gorkamunoz.github.io',
                'git_url': 'https://github.com/gorkamunoz/nbdev-doc-test',
                'lib_path': 'nbdev_doc_test'},
  'syms': { 'nbdev_doc_test\\core': { 'nbdev_doc_test\\core.foo': ( 'https://gorkamunoz.github.io/core.html#foo',
                                                                    'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\core.py#L7')},
            'nbdev_doc_test\\datasets_challenge': { 'nbdev_doc_test\\datasets_challenge._df_andi2': ( 'https://gorkamunoz.github.io/datasets_challenge.html#_df_andi2',
                                                                                                      'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\datasets_challenge.py#L381'),
                                                    'nbdev_doc_test\\datasets_challenge._df_andi2.__init__': ( 'https://gorkamunoz.github.io/datasets_challenge.html#__init__',
                                                                                                               'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\datasets_challenge.py#L383'),
                                                    'nbdev_doc_test\\datasets_challenge._get_dic_andi2': ( 'https://gorkamunoz.github.io/datasets_challenge.html#_get_dic_andi2',
                                                                                                           'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\datasets_challenge.py#L399'),
                                                    'nbdev_doc_test\\datasets_challenge.challenge_2020_dataset': ( 'https://gorkamunoz.github.io/datasets_challenge.html#challenge_2020_dataset',
                                                                                                                   'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\datasets_challenge.py#L20'),
                                                    'nbdev_doc_test\\datasets_challenge.challenge_2022_dataset': ( 'https://gorkamunoz.github.io/datasets_challenge.html#challenge_2022_dataset',
                                                                                                                   'https://github.com/gorkamunoz/nbdev-doc-test/blob/master/nbdev_doc_test\\datasets_challenge.py#L474')}}}