# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-doc-test',
                'doc_host': 'https://gorkamunoz.github.io',
                'git_url': 'https://github.com/gorkamunoz/nbdev-doc-test',
                'lib_path': 'nbdev_doc_test'},
  'syms': { 'nbdev_doc_test.core': {'nbdev_doc_test.core.foo': ('core.html#foo', 'nbdev_doc_test/core.py')},
            'nbdev_doc_test.other': {'nbdev_doc_test.other.play_video': ('other.html#play_video', 'nbdev_doc_test/other.py')}}}