# AUTOGENERATED! DO NOT EDIT! File to edit: ../source_nbs/lib_nbs/01_other.ipynb.

# %% auto 0
__all__ = ['play_video']

# %% ../source_nbs/lib_nbs/01_other.ipynb 2
import matplotlib.animation as animation
import matplotlib.pyplot as plt
#from IPython.display import HTML
import numpy as np

# %% ../source_nbs/lib_nbs/01_other.ipynb 4
def play_video(video:int|float, # a video blablabla
               figsize:tuple=(5, 5), # the size of the fig
               fps:int=10, # the fps
              ) -> int: # a number


    fig = plt.figure(figsize=figsize)
    images = []
    plt.axis("off")

    for image in video:
        images.append([plt.imshow(image[:, :, 0], cmap="gray")])

    anim = animation.ArtistAnimation(
        fig, images, interval=1e3 / fps, blit=True, repeat_delay=0
    )

    html = HTML(anim.to_jshtml())
    display(html)
    plt.close()
    
    return 123
